// Kategorize edilmiş araç markaları
export interface VehicleBrandCategory {
  name: string;
  brands: string[];
}

export const vehicleBrandCategories: VehicleBrandCategory[] = [
  {
    name: "Binek Araçlar",
    brands: [
      "Audi",
      "BMW",
      "Mercedes-Benz",
      "Volkswagen",
      "Toyota",
      "Ford",
      "Renault",
      "Fiat",
      "Opel",
      "Peugeot",
      "Citroën",
      "Hyundai",
      "Kia",
      "Honda",
      "Nissan",
      "Mazda",
      "Suzuki",
      "Mitsubishi",
      "Subaru",
      "Skoda",
      "Seat",
      "Volvo",
      "Mini",
      "Smart",
      "Dacia",
      "Lada",
      "Tofaş",
      "Dacia",
      "Chevrolet",
      "Jeep",
      "Chrysler",
      "Dodge",
      "Jaguar",
      "Land Rover",
      "Range Rover",
      "Porsche",
      "Bentley",
      "Rolls-Royce",
      "Maserati",
      "Ferrari",
      "Lamborghini",
      "Aston Martin",
      "McLaren",
      "Alfa Romeo",
      "Lancia",
      "Infiniti",
      "Lexus",
      "Acura",
      "Genesis",
      "DS",
    ],
  },
  {
    name: "Elektrikli Araçlar",
    brands: [
      "Tesla",
      "BYD",
      "MG",
      "Polestar",
      "Nio",
      "Xpeng",
      "Rivian",
      "Lucid",
      "Fisker",
      "Rimac",
      "Zeekr",
      "Audi e-tron",
      "BMW i",
      "Mercedes-Benz EQ",
      "Volkswagen ID",
      "Hyundai IONIQ",
      "Kia EV",
      "Nissan Leaf",
      "Chevrolet Bolt",
      "Ford Mustang Mach-E",
      "Ford F-150 Lightning",
      "Volvo XC40 Recharge",
      "Porsche Taycan",
      "Jaguar I-PACE",
      "Mini Electric",
      "Smart EQ",
      "Renault Zoe",
      "Peugeot e-208",
      "Opel Corsa-e",
      "Citroën ë-C4",
      "DS 3 Crossback E-Tense",
    ],
  },
  {
    name: "Tır/Kamyon",
    brands: [
      "Mercedes-Benz",
      "Volvo",
      "Scania",
      "MAN",
      "Iveco",
      "DAF",
      "Renault Trucks",
      "Isuzu",
      "Hino",
      "Mitsubishi Fuso",
      "Ford Trucks",
      "Freightliner",
      "Peterbilt",
      "Kenworth",
      "Mack",
      "Western Star",
      "International",
      "Navistar",
      "Caterpillar",
      "Komatsu",
      "Tata",
      "Ashok Leyland",
      "Eicher",
      "Mahindra",
      "BMC",
      "Otokar",
      "Temsa",
      "Ford Cargo",
    ],
  },
  {
    name: "Karavan",
    brands: [
      "Fiat",
      "Ford",
      "Mercedes-Benz",
      "Volkswagen",
      "Hymer",
      "Knaus",
      "Bürstner",
      "Dethleffs",
      "Eriba",
      "Hobby",
      "LMC",
      "Niesmann+Bischoff",
      "Tabbert",
      "Weinsberg",
      "Adria",
      "Bailey",
      "Swift",
      "Elddis",
      "Lunar",
      "Coachman",
      "Airstream",
      "Winnebago",
      "Jayco",
      "Forest River",
      "Grand Design",
      "Keystone",
      "Dutchmen",
      "Thor",
      "Newmar",
      "Tiffin",
      "Entegra",
      "Renault",
      "Peugeot",
      "Citroën",
      "Opel",
    ],
  },
  {
    name: "Motosiklet",
    brands: [
      "Honda",
      "Yamaha",
      "Kawasaki",
      "Suzuki",
      "BMW",
      "Ducati",
      "Harley-Davidson",
      "Triumph",
      "KTM",
      "Aprilia",
      "Moto Guzzi",
      "MV Agusta",
      "Benelli",
      "Piaggio",
      "Vespa",
      "Husqvarna",
      "GasGas",
      "Beta",
      "Sherco",
      "Kymco",
      "Sym",
      "Bajaj",
      "TVS",
      "Hero",
      "Royal Enfield",
      "Indian",
      "Victory",
      "Zero",
      "Energica",
      "LiveWire",
    ],
  },
  {
    name: "Hafif Ticari",
    brands: [
      "Ford Transit",
      "Mercedes-Benz Sprinter",
      "Volkswagen Crafter",
      "Iveco Daily",
      "Renault Master",
      "Fiat Ducato",
      "Peugeot Boxer",
      "Citroën Jumper",
      "Opel Movano",
      "Toyota Hiace",
      "Nissan NV200",
      "Hyundai H350",
      "Kia Bongo",
      "Isuzu D-Max",
      "Mitsubishi L200",
      "Ford Ranger",
      "Volkswagen Amarok",
      "Mercedes-Benz Vito",
      "Renault Trafic",
      "Fiat Doblo",
      "Peugeot Partner",
      "Citroën Berlingo",
      "Opel Combo",
      "Ford Transit Connect",
      "Volkswagen Caddy",
      "Toyota Proace",
      "Nissan Primastar",
    ],
  },
];

// Tüm markaları tek bir array'de döndür (dropdown için)
export function getAllBrands(): string[] {
  return vehicleBrandCategories.flatMap((category) => category.brands);
}

// Marka kategorisini bul
export function getBrandCategory(brand: string): string | null {
  for (const category of vehicleBrandCategories) {
    if (category.brands.includes(brand)) {
      return category.name;
    }
  }
  return null;
}
